apiVersion: v1
name: shop
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 12.8.1
    repository: https://charts.bitnami.com/bitnami